### ISSUE TITLE
Fix python examples to reflect the latest changes

### ISSUE THREAD

**Issue by jarkenau** [agri-gaia/seerep#249]
Some python examples broke due to the introduction of label categories and a project now having geodetic coordinates. The following this need to be done: 

- [x] `fb_sendPointsBasedOnImageInstance` needs to handle 2D bounding boxes with categories
- [x] same for `loadSimulatedData` (#251)
- [x] `loadSimulatedDataWithInstancePosition`, project creation must be updated (#254)
- [x] `querySimulatedData` has some bug, fix it (#254)

**Comment by jarkenau** [comment]
Finished by the linked PRs
